# Generated by Django 3.2.4 on 2021-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=10)),
                ('Lastname', models.CharField(max_length=10)),
                ('m_id', models.IntegerField()),
                ('m_phone_no', models.IntegerField()),
                ('m_salary', models.IntegerField()),
            ],
        ),
    ]
